### ISSUE TITLE
EEPROM.h: No such file or directory with ArduinoCore-mbed

### ISSUE THREAD

**Issue by SamHalvoe** [bblanchon/ArduinoStreamUtils#31]
Hello Beniot,

First, I want to thank you for the quick fix of issue [reference to '__FlashStringHelper' is ambiguous with arduino-pico](https://github.com/bblanchon/ArduinoStreamUtils/issues/30).
The fix seems to have introduced an error with the other core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed) for the raspberry pi pico. When I compile with StreamUtils version 1.7.2 and core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed), I get the error message "EEPROM.h: No such file or directory".
The header EEPROM.h is not present in the core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed). I assume [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed) does not support EEPROM or EEPROM emulation (see [EEPROM issue](https://github.com/arduino/ArduinoCore-mbed/issues/205)).
With StreamUtils version 1.7.1 and the core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed) it compiles just fine.
Reproduction of the error should be possible with an empty sketch, just include <StreamUtils.h> (version 1.7.2) and compile with core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed).
Could you have a look?

Best regards,
Samuel

PS: I use both cores for different projects with the pico, therefore I notice corresponding differences. (;

complete compiler output:
```
In file included from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.hpp:17:0,
                 from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.h:5,
                 from C:\Users\samue\AppData\Local\Temp\.arduinoIDE-unsaved202328-15616-1up951o.5wvm\sketch_mar8a\sketch_mar8a.ino:1:
c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils/Streams/EepromStream.hpp:11:10: fatal error: EEPROM.h: No such file or directory
 #include <EEPROM.h>
          ^~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
```

**Comment by bblanchon** [comment]
Hello Sameul ;-)

Thank you very much for reporting this bug.
It should be fixed in 1.7.3.

Best regards,
Benoit
